version: "3"
services:
  node-bootstrap:
    image: aceberg/node-bootstrap
    restart: unless-stopped
    ports:
    - 8850:8850
  wyl:
    image: aceberg/watchyourlan:v2
    network_mode: "host"      
    restart: unless-stopped
    command: "-n http://localhost:8850"   # put your server IP or DNS name here
    depends_on:
      - node-bootstrap
    volumes:
    - ~/.dockerdata/wyl:/data/WatchYourLAN
    environment:
      TZ: Asia/Tokyo             # required: needs your TZ for correct time
      IFACES: "localhost"  # required: 1 or more interface
      HOST: "192.168.56.1"                   # optional, default: 0.0.0.0
      PORT: "8840"                      # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 120
      SHOUTRRR_URL: ""                  # optional, set url to notify
      THEME: "sand"                     # optional
      COLOR: "dark"                     # optional